# Generated by Django 4.2 on 2023-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bngjobs",
            name="address",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="hydjobs",
            name="address",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="punejobs",
            name="address",
            field=models.CharField(max_length=64),
        ),
    ]
